<!DOCTYPE html>
<html lang="ja-JP">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta http-equiv="Content-Language" content="ja-JP">
  <link rel="stylesheet" type="text/css" href="../style.css">
  <link rel="icon" type="image/png" href="../rurema.png">
  
  <title>class LocalJumpError (Ruby 2.0.0)</title>
</head>
<body>

<p>
<a href="../doc/index.html">Ruby 2.0.0 リファレンスマニュアル</a>
&gt; <a href="../library/index.html">ライブラリ一覧</a>
&gt; <a href="../library/_builtin.html">組み込みライブラリ</a>
&gt; LocalJumpErrorクラス
</p>


<h1>class LocalJumpError</h1>
<p>


クラスの継承リスト: LocalJumpError

      &lt; <a href="../class/-standard-error.html">StandardError</a>
      

      &lt; <a href="../class/-exception.html">Exception</a>
      

      &lt; <a href="../class/-object.html">Object</a>
      

      &lt; <a href="../class/-kernel.html">Kernel</a>
      

      &lt; <a href="../class/-basic-object.html">BasicObject</a>
      







</p>

<h2>要約</h2>
<p>
ある <a href="../class/-proc.html">Proc</a> オブジェクトの作成元スコープがすでに終了しているとき、
その <a href="../class/-proc.html">Proc</a> オブジェクト内で
return, break, retry のいずれかを実行すると発生します。
</p>
<p>
<a href="../class/-proc.html">Proc</a> の例を参照してください。
</p>



<h2>目次</h2>
<dl>

<dt>インスタンスメソッド</dt>
<dd>

<a href="#I_EXIT_VALUE">exit_value</a>

<a href="#I_REASON">reason</a>

</dd>

</dl>


<h2>インスタンスメソッド</h2>
<dl>

<dt class="method-heading" id="I_EXIT_VALUE"><code>exit_value -&gt; object</code><span class="permalink">[<a href="../method/-local-jump-error/i/exit_value.html">permalink</a>][<a href="http://docs.ruby-lang.org/en/2.0.0/LocalJumpError.html#method-i-exit_value">rdoc</a>]</span></dt>
<dd class="method-description">
<p>
例外 LocalJumpError を発生する原因となった
break や return に渡した値を返します。
</p>
<p>
例:
</p>
<pre>
def foo
  proc { return 10 }
end

begin
  foo.call
rescue LocalJumpError =&gt; err
  p err              # =&gt; #&lt;LocalJumpError: return from block-closure&gt;
  p err.reason       # =&gt; :return
  p err.exit_value   # =&gt; 10
end

begin
  Block.new { break 5 }.call
rescue LocalJumpError =&gt; err
  p err              # =&gt; #&lt;LocalJumpError: break from block-closure&gt;
  p err.reason       # =&gt; :break
  p err.exit_value   # =&gt; 5
end
</pre>
</dd>


<dt class="method-heading" id="I_REASON"><code>reason -&gt; Symbol</code><span class="permalink">[<a href="../method/-local-jump-error/i/reason.html">permalink</a>][<a href="http://docs.ruby-lang.org/en/2.0.0/LocalJumpError.html#method-i-reason">rdoc</a>]</span></dt>
<dd class="method-description">
<p>
例外を発生させた原因をシンボルで返します。
</p>
<p>
返す値は以下のいずれかです。
</p>
<ul>
<li>:break</li>
<li>:redo</li>
<li>:retry</li>
<li>:next</li>
<li>:return</li>
</ul>
<p>
例:
</p>
<pre>
def foo
  proc { return 10 }
end

begin
  foo.call
rescue LocalJumpError =&gt; err
  p err              # =&gt; #&lt;LocalJumpError: return from block-closure&gt;
  p err.reason       # =&gt; :return
  p err.exit_value   # =&gt; 10
end

begin
  Block.new { break 5 }.call
rescue LocalJumpError =&gt; err
  p err              # =&gt; #&lt;LocalJumpError: break from block-closure&gt;
  p err.reason       # =&gt; :break
  p err.exit_value   # =&gt; 5
end
</pre>
</dd>


</dl>



<div id="footer">
  <a rel="license" href="https://creativecommons.org/licenses/by/3.0/">
    <img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/3.0/88x31.png" />
  </a>
</div>
</body>
</html>
