<!DOCTYPE html>
<html lang="ja-JP">
<head>

<meta name="robots" content="noindex">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="../../../style.css">
<link rel="stylesheet" href="../../../syntax-highlight.css">
<link rel="icon" type="image/png" href="../../../rurema.png">

<title>Exception2MessageMapper#Fail (Ruby 2.6.10 リファレンスマニュアル)</title>
<meta name="description" content="@param exception_class 例外クラス。">
<script src="../../../script.js"></script>
</head>
<body>


<header>
  <nav>
    <ol class="inline-breadcrumb-list">
      <li>
        <a href="../../../doc/index.html">Ruby 2.6.10 リファレンスマニュアル</a>
      </li>
      <li>
        <a href="../../../library/index.html">ライブラリ一覧</a>
      </li>
      <li>
        <a href="../../../library/e2mmap.html">e2mmapライブラリ</a>
      </li>
      <li>
        <a href="../../../class/-exception2-message-mapper.html">Exception2MessageMapperモジュール</a>
      </li>
      <li>
        Fail 
      </li>
    </ol>
  </nav>

<h1>instance method Exception2MessageMapper#Fail</h1>
</header>

<main>
<dl class="methodlist">

<dt class="method-heading" id="I_-FAIL"><code>Raise(exception_class = nil, *rest) -&gt; ()</code><span class="permalink">[<a href="../../../method/-exception2-message-mapper/i/-fail.html">permalink</a>][<a href="https://docs.ruby-lang.org/en/2.6.10/Exception2MessageMapper.html#method-i-Fail">rdoc</a>]</span></dt>
<dt class="method-heading"><code>Fail(exception_class = nil, *rest) -&gt; ()</code></dt>
<dd class="method-description">
<p>
登録されている情報を使用して、例外を発生させます。
</p>
<dl>
<dt class='method-param'>[PARAM] exception_class:</dt>
<dd>
例外クラス。
</dd>
<dt class='method-param'>[PARAM] rest:</dt>
<dd>
メッセージに埋め込む値。
</dd>
<dt>[EXCEPTION] Exception2MessageMapper::ErrNotRegisteredException:</dt>
<dd>
指定された例外クラスに対応するメッセージが存在しない場合に発生します。
</dd>
</dl>
<p>
例:
</p>
<pre>
class Foo
  extend Exception2MessageMapper
  p def_exception :NewExceptionClass, &quot;message...%d, %d and %d&quot; # =&gt;

  def foo
    Raise NewExceptionClass, 1, 2, 3
  end
end

Foo.new().foo() #=&gt; in `Raise': message...1, 2 and 3 (Foo::NewExceptionClass)
                #   という例外が発生します。

Foo.Raise Foo::NewExceptionClass, 1, 3, 5  #=&gt; in `Raise': message...1, 3 and 5 (Foo::NewExceptionClass)
                                           #   という例外が発生します。
</pre>
</dd>


</dl>
</main>

<footer id="footer">
  <a rel="license" href="https://creativecommons.org/licenses/by/3.0/">
    <img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/3.0/88x31.png" />
  </a>

  <a href="https://github.com/rurema/doctree/issues/new" id="feedback-link">フィードバックを送る</a>
  
  <script>if (window.URLSearchParams) { document.getElementById("feedback-link").search = new URLSearchParams({'body': document.location}); }</script>
</footer>
</body>
</html>
